// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: exchange.proto

package exchangepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Оффер на обмен книги
type ExchangeOffer struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OwnerId          string                 `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`                      // тот, кто создал оффер
	CounterpartyId   string                 `protobuf:"bytes,3,opt,name=counterparty_id,json=counterpartyId,proto3" json:"counterparty_id,omitempty"` // с кем хотят обменяться
	OfferedBookIds   []string               `protobuf:"bytes,4,rep,name=offered_book_ids,json=offeredBookIds,proto3" json:"offered_book_ids,omitempty"`
	RequestedBookIds []string               `protobuf:"bytes,5,rep,name=requested_book_ids,json=requestedBookIds,proto3" json:"requested_book_ids,omitempty"`
	Status           string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"` // PENDING, ACCEPTED, DECLINED
	CreatedAt        string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        string                 `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ExchangeOffer) Reset() {
	*x = ExchangeOffer{}
	mi := &file_exchange_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeOffer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeOffer) ProtoMessage() {}

func (x *ExchangeOffer) ProtoReflect() protoreflect.Message {
	mi := &file_exchange_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeOffer.ProtoReflect.Descriptor instead.
func (*ExchangeOffer) Descriptor() ([]byte, []int) {
	return file_exchange_proto_rawDescGZIP(), []int{0}
}

func (x *ExchangeOffer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ExchangeOffer) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *ExchangeOffer) GetCounterpartyId() string {
	if x != nil {
		return x.CounterpartyId
	}
	return ""
}

func (x *ExchangeOffer) GetOfferedBookIds() []string {
	if x != nil {
		return x.OfferedBookIds
	}
	return nil
}

func (x *ExchangeOffer) GetRequestedBookIds() []string {
	if x != nil {
		return x.RequestedBookIds
	}
	return nil
}

func (x *ExchangeOffer) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ExchangeOffer) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ExchangeOffer) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type CreateOfferRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	OwnerId          string                 `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`                      // тот, кто создаёт оффер
	CounterpartyId   string                 `protobuf:"bytes,2,opt,name=counterparty_id,json=counterpartyId,proto3" json:"counterparty_id,omitempty"` // с кем хотят обменяться
	OfferedBookIds   []string               `protobuf:"bytes,3,rep,name=offered_book_ids,json=offeredBookIds,proto3" json:"offered_book_ids,omitempty"`
	RequestedBookIds []string               `protobuf:"bytes,4,rep,name=requested_book_ids,json=requestedBookIds,proto3" json:"requested_book_ids,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateOfferRequest) Reset() {
	*x = CreateOfferRequest{}
	mi := &file_exchange_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOfferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOfferRequest) ProtoMessage() {}

func (x *CreateOfferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_exchange_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOfferRequest.ProtoReflect.Descriptor instead.
func (*CreateOfferRequest) Descriptor() ([]byte, []int) {
	return file_exchange_proto_rawDescGZIP(), []int{1}
}

func (x *CreateOfferRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *CreateOfferRequest) GetCounterpartyId() string {
	if x != nil {
		return x.CounterpartyId
	}
	return ""
}

func (x *CreateOfferRequest) GetOfferedBookIds() []string {
	if x != nil {
		return x.OfferedBookIds
	}
	return nil
}

func (x *CreateOfferRequest) GetRequestedBookIds() []string {
	if x != nil {
		return x.RequestedBookIds
	}
	return nil
}

type OfferID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OfferID) Reset() {
	*x = OfferID{}
	mi := &file_exchange_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OfferID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfferID) ProtoMessage() {}

func (x *OfferID) ProtoReflect() protoreflect.Message {
	mi := &file_exchange_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfferID.ProtoReflect.Descriptor instead.
func (*OfferID) Descriptor() ([]byte, []int) {
	return file_exchange_proto_rawDescGZIP(), []int{2}
}

func (x *OfferID) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type OfferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offer         *ExchangeOffer         `protobuf:"bytes,1,opt,name=offer,proto3" json:"offer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OfferResponse) Reset() {
	*x = OfferResponse{}
	mi := &file_exchange_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OfferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfferResponse) ProtoMessage() {}

func (x *OfferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_exchange_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfferResponse.ProtoReflect.Descriptor instead.
func (*OfferResponse) Descriptor() ([]byte, []int) {
	return file_exchange_proto_rawDescGZIP(), []int{3}
}

func (x *OfferResponse) GetOffer() *ExchangeOffer {
	if x != nil {
		return x.Offer
	}
	return nil
}

type OfferList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offers        []*ExchangeOffer       `protobuf:"bytes,1,rep,name=offers,proto3" json:"offers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OfferList) Reset() {
	*x = OfferList{}
	mi := &file_exchange_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OfferList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfferList) ProtoMessage() {}

func (x *OfferList) ProtoReflect() protoreflect.Message {
	mi := &file_exchange_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfferList.ProtoReflect.Descriptor instead.
func (*OfferList) Descriptor() ([]byte, []int) {
	return file_exchange_proto_rawDescGZIP(), []int{4}
}

func (x *OfferList) GetOffers() []*ExchangeOffer {
	if x != nil {
		return x.Offers
	}
	return nil
}

type UserID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserID) Reset() {
	*x = UserID{}
	mi := &file_exchange_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserID) ProtoMessage() {}

func (x *UserID) ProtoReflect() protoreflect.Message {
	mi := &file_exchange_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserID.ProtoReflect.Descriptor instead.
func (*UserID) Descriptor() ([]byte, []int) {
	return file_exchange_proto_rawDescGZIP(), []int{5}
}

func (x *UserID) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_exchange_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_exchange_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_exchange_proto_rawDescGZIP(), []int{6}
}

// Новый запрос для принятия оффера
type AcceptOfferRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OfferId       string                 `protobuf:"bytes,1,opt,name=offer_id,json=offerId,proto3" json:"offer_id,omitempty"`             // ID оффера
	RequesterId   string                 `protobuf:"bytes,2,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"` // подтверждающий (тот же, что counterparty_id)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptOfferRequest) Reset() {
	*x = AcceptOfferRequest{}
	mi := &file_exchange_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptOfferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptOfferRequest) ProtoMessage() {}

func (x *AcceptOfferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_exchange_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptOfferRequest.ProtoReflect.Descriptor instead.
func (*AcceptOfferRequest) Descriptor() ([]byte, []int) {
	return file_exchange_proto_rawDescGZIP(), []int{7}
}

func (x *AcceptOfferRequest) GetOfferId() string {
	if x != nil {
		return x.OfferId
	}
	return ""
}

func (x *AcceptOfferRequest) GetRequesterId() string {
	if x != nil {
		return x.RequesterId
	}
	return ""
}

var File_exchange_proto protoreflect.FileDescriptor

const file_exchange_proto_rawDesc = "" +
	"\n" +
	"\x0eexchange.proto\x12\bexchange\"\x91\x02\n" +
	"\rExchangeOffer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\tR\aownerId\x12'\n" +
	"\x0fcounterparty_id\x18\x03 \x01(\tR\x0ecounterpartyId\x12(\n" +
	"\x10offered_book_ids\x18\x04 \x03(\tR\x0eofferedBookIds\x12,\n" +
	"\x12requested_book_ids\x18\x05 \x03(\tR\x10requestedBookIds\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\tR\tupdatedAt\"\xb0\x01\n" +
	"\x12CreateOfferRequest\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\tR\aownerId\x12'\n" +
	"\x0fcounterparty_id\x18\x02 \x01(\tR\x0ecounterpartyId\x12(\n" +
	"\x10offered_book_ids\x18\x03 \x03(\tR\x0eofferedBookIds\x12,\n" +
	"\x12requested_book_ids\x18\x04 \x03(\tR\x10requestedBookIds\"\x19\n" +
	"\aOfferID\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\">\n" +
	"\rOfferResponse\x12-\n" +
	"\x05offer\x18\x01 \x01(\v2\x17.exchange.ExchangeOfferR\x05offer\"<\n" +
	"\tOfferList\x12/\n" +
	"\x06offers\x18\x01 \x03(\v2\x17.exchange.ExchangeOfferR\x06offers\"!\n" +
	"\x06UserID\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\a\n" +
	"\x05Empty\"R\n" +
	"\x12AcceptOfferRequest\x12\x19\n" +
	"\boffer_id\x18\x01 \x01(\tR\aofferId\x12!\n" +
	"\frequester_id\x18\x02 \x01(\tR\vrequesterId2\xba\x03\n" +
	"\x0fExchangeService\x12D\n" +
	"\vCreateOffer\x12\x1c.exchange.CreateOfferRequest\x1a\x17.exchange.OfferResponse\x126\n" +
	"\bGetOffer\x12\x11.exchange.OfferID\x1a\x17.exchange.OfferResponse\x129\n" +
	"\x10ListOffersByUser\x12\x10.exchange.UserID\x1a\x13.exchange.OfferList\x129\n" +
	"\x11ListPendingOffers\x12\x0f.exchange.Empty\x1a\x13.exchange.OfferList\x12D\n" +
	"\vAcceptOffer\x12\x1c.exchange.AcceptOfferRequest\x1a\x17.exchange.OfferResponse\x12:\n" +
	"\fDeclineOffer\x12\x11.exchange.OfferID\x1a\x17.exchange.OfferResponse\x121\n" +
	"\vDeleteOffer\x12\x11.exchange.OfferID\x1a\x0f.exchange.EmptyBTZRgithub.com/OshakbayAigerim/read_space/exchange_service/proto/exchangepb;exchangepbb\x06proto3"

var (
	file_exchange_proto_rawDescOnce sync.Once
	file_exchange_proto_rawDescData []byte
)

func file_exchange_proto_rawDescGZIP() []byte {
	file_exchange_proto_rawDescOnce.Do(func() {
		file_exchange_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_exchange_proto_rawDesc), len(file_exchange_proto_rawDesc)))
	})
	return file_exchange_proto_rawDescData
}

var file_exchange_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_exchange_proto_goTypes = []any{
	(*ExchangeOffer)(nil),      // 0: exchange.ExchangeOffer
	(*CreateOfferRequest)(nil), // 1: exchange.CreateOfferRequest
	(*OfferID)(nil),            // 2: exchange.OfferID
	(*OfferResponse)(nil),      // 3: exchange.OfferResponse
	(*OfferList)(nil),          // 4: exchange.OfferList
	(*UserID)(nil),             // 5: exchange.UserID
	(*Empty)(nil),              // 6: exchange.Empty
	(*AcceptOfferRequest)(nil), // 7: exchange.AcceptOfferRequest
}
var file_exchange_proto_depIdxs = []int32{
	0, // 0: exchange.OfferResponse.offer:type_name -> exchange.ExchangeOffer
	0, // 1: exchange.OfferList.offers:type_name -> exchange.ExchangeOffer
	1, // 2: exchange.ExchangeService.CreateOffer:input_type -> exchange.CreateOfferRequest
	2, // 3: exchange.ExchangeService.GetOffer:input_type -> exchange.OfferID
	5, // 4: exchange.ExchangeService.ListOffersByUser:input_type -> exchange.UserID
	6, // 5: exchange.ExchangeService.ListPendingOffers:input_type -> exchange.Empty
	7, // 6: exchange.ExchangeService.AcceptOffer:input_type -> exchange.AcceptOfferRequest
	2, // 7: exchange.ExchangeService.DeclineOffer:input_type -> exchange.OfferID
	2, // 8: exchange.ExchangeService.DeleteOffer:input_type -> exchange.OfferID
	3, // 9: exchange.ExchangeService.CreateOffer:output_type -> exchange.OfferResponse
	3, // 10: exchange.ExchangeService.GetOffer:output_type -> exchange.OfferResponse
	4, // 11: exchange.ExchangeService.ListOffersByUser:output_type -> exchange.OfferList
	4, // 12: exchange.ExchangeService.ListPendingOffers:output_type -> exchange.OfferList
	3, // 13: exchange.ExchangeService.AcceptOffer:output_type -> exchange.OfferResponse
	3, // 14: exchange.ExchangeService.DeclineOffer:output_type -> exchange.OfferResponse
	6, // 15: exchange.ExchangeService.DeleteOffer:output_type -> exchange.Empty
	9, // [9:16] is the sub-list for method output_type
	2, // [2:9] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_exchange_proto_init() }
func file_exchange_proto_init() {
	if File_exchange_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_exchange_proto_rawDesc), len(file_exchange_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_exchange_proto_goTypes,
		DependencyIndexes: file_exchange_proto_depIdxs,
		MessageInfos:      file_exchange_proto_msgTypes,
	}.Build()
	File_exchange_proto = out.File
	file_exchange_proto_goTypes = nil
	file_exchange_proto_depIdxs = nil
}
